import "../../styles/globals.css";
import "../../styles/sideMenuOverflowStyle.css";
import { AppProps } from "next/app";
import ResponsiveDrawer from "../layouts/sideBar/sideBar";
import Box from "@mui/material/Box";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {

  return (
    <Provider store={store}>
      <Head>
        <title>In-Out web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ display: "flex", background: "#111315", height: "100%", minHeight: "100vh" }}>
        <ResponsiveDrawer></ResponsiveDrawer>
        <Component {...pageProps} />
      </Box>
    </Provider>
  );
}

export default MyApp;
